/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_panjq_opencv_alg_ImagePro */

#ifndef _Included_com_panjq_opencv_alg_ImagePro
#define _Included_com_panjq_opencv_alg_ImagePro
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_panjq_opencv_alg_ImagePro
 * Method:    jniImagePro1
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_panjq_opencv_alg_ImagePro_jniImagePro1
  (JNIEnv *, jobject, jintArray, jint, jint);

/*
 * Class:     com_panjq_opencv_alg_ImagePro
 * Method:    jniImagePro2
 * Signature: (Lcom/panjq/opencv/alg/ImageData;)Lcom/panjq/opencv/alg/ImageData;
 */
JNIEXPORT jobject JNICALL Java_com_panjq_opencv_alg_ImagePro_jniImagePro2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_panjq_opencv_alg_ImagePro
 * Method:    jniImagePro3
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_panjq_opencv_alg_ImagePro_jniImagePro3
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
